# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

project = '张盛宇的简历'
author = '张盛宇'
copyright = '2025, ' + author

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinxcontrib.email',
    'sphinx.ext.githubpages',
    'sphinx_last_updated_by_git',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store', 'README.rst']

# Options for internationalisation -------------------------------------------

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

# Directories in which to search for additional message catalogs (see language),
# relative to the source directory. The directories on this path are
# searched by the gettext module.
locale_dirs = ['locale/']

gettext_allow_fuzzy_translations = True

# -- Options for HTML output -------------------------------------------------

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = ['custom.css']

html_baseurl = 'https://silverrainz.me/resume'
html_title = ''
html_favicon = '_static/favicon.png'

# HTML theme configuration
html_theme = 'pydata_sphinx_theme'
html_theme_options = {}

html_sidebars = {}

# Show only Single page
## Hide navbar.
html_theme_options['navbar_start'] = []
html_theme_options['navbar_center'] = []
html_theme_options['navbar_end'] = ['navbar-icon-links']
html_theme_options['navbar_persistent'] = []
## Hide sidebars.
## See also https://pydata-sphinx-theme.readthedocs.io/en/latest/examples/no-sidebar.html
html_sidebars['*'] = [] # primary
html_theme_options['secondary_sidebar_items'] = {'*': []} # secondary
## Unrelated elements
html_theme_options['show_prev_next'] = False,

# Custom footer.
html_theme_options['footer_start'] = ['theme-switcher'] # TODO: 'version-switcher'
html_theme_options['footer_end'] = ['copyright', 'last-updated', 'sphinx-version', 'theme-version']

html_last_updated_fmt = '%Y-%m-%d'

# -- Options for LaTeX output -------------------------------------------------

latex_toplevel_sectioning = 'section'
latex_theme = 'howto'
latex_elements = {
    'papersize': 'a4paper',

    'preamble': r'''
        \setcounter{secnumdepth}{0}
        \date{}
    ''',

    'maketitle': r'''
            \title{
                \textbf{@AUTHOR_PLACEHOLDER@}
                \vspace{-1em}
            }
            \author{\vspace{-2em}}
            \date{\vspace{-2em}}
            \maketitle
    ''',
    'makeindex' : r'',
    'printindex' : r'',
    'tableofcontents': r''
}

# -- Per-extension configuration ---------------------------------------------------

extensions.append('sphinxcontrib.gtagjs')
gtagjs_ids = ['G-FYHS50G6DL']

extensions.append('sphinxnotes.snippet')
snippet_patterns = { 'd': ['.*'] }

def setup(app):
    # Setup PDF title according to language.
    titles = {
        'zh_CN': author,
        'en': 'Shengyu Zhang',
    }
    placeholder = '@AUTHOR_PLACEHOLDER@'
    title = titles[app.config.language]
    app.config.latex_elements['maketitle'] = latex_elements['maketitle'].replace(placeholder, title)
